### ISSUE TITLE
Executable no longer executable after unzip

### ISSUE THREAD

**Issue by kontur** [linkedin/shiv#100]
It appears a module I am shiv'ing includes a file that loses its executable flag when unzipped by the shiv bootstrapper. Is this something that is expected behavior from your side?

From the discussion in the packaged module where this happens:

>  shiv simply calls extract method of ZipFile, thus it loses any previous exectutable permissions. It should instead do something similar to what the pip installer does when unpacking a wheel (which is also a zip file)

For more [details](https://github.com/adobe-type-tools/psautohint/issues/166#issuecomment-497746566).

**Comment by anthrotype** [comment]
simply extracting a ZipFile seems to lose all exectuable permissions.
I see that when the pip installer unzips a file, it also restores any executable permissions for regular files, see:
https://github.com/pypa/pip/blob/83d813c01e8debe7fd2bee4af106da06c915d3fc/src/pip/_internal/utils/misc.py#L523-L566

Shiv should probably do something similar.

The above mentioned package work without issues when installed in a normal, non-shiv environment.

**Comment by anthrotype** [comment]
For background, this `psautohint` package includes a native executable (using `package_data` to bundle it in the wheel).

**Comment by lorencarvalho** [comment]
hi @kontur thanks for reporting! I've just done a quick repro and ref implementation of a fix in #101 

one thing to keep in mind when you have applications that make subprocess calls, you may want to invoke `shiv` with the `-E` or `--extend-pythonpath` option, to ensure that subprocesses have access to the included dependencies. 

I want to add a test for this functionality before I push and cut a release, I hope to get to it shortly

**Comment by anthrotype** [comment]
That was quick, thank you!
The subprocess is question is a C executable without any dependencies on external libraries.

**Comment by lorencarvalho** [comment]
released to pypi @ `0.0.48`

**Comment by anthrotype** [comment]
thansk a lot

**Comment by kontur** [comment]
👍 Fantastic, thanks for the quick action!
