### ISSUE TITLE
Problems with Multiprocessing

### ISSUE THREAD

**Issue by smalltoe** [linkedin/shiv#105]
I tried to pack a script that uses multiprocessing. Unfortunately I was not successful executing the package. The script is of the following sort:
```python
import multiprocessing

def process_image(chunk):
    for r in chunk:
        print("%s" %r)

chunks=[[1,2,3,4],['one','two','three','four']]

multiprocessing.freeze_support()

pool = multiprocessing.Pool(processes=2)

pool.map(process_image, chunks)
```

If run in the  Linux command line there is no issue - but as soon as I pack it with shiv it hangs at `pool = multiprocessing.Pool(processes=2)` . I am using a Python 3.6.3 interpreter. Any ideas?

**Comment by lorencarvalho** [comment]
hi @smalltoe 

Thanks for the report, I attempted to reproduce the issue you are describing and I cannot reproduce:

```
darwin /var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmp.ijKV32fk $ cat hello/__init__.py
import multiprocessing


def process_image(chunk):
    for r in chunk:
        print("%s" %r)


def main():
    chunks=[[1,2,3,4],['one','two','three','four']]

    multiprocessing.freeze_support()

    pool = multiprocessing.Pool(processes=2)

    pool.map(process_image, chunks)
darwin /var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmp.ijKV32fk $ shiv -o test -c hello .
Processing /private/var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmp.ijKV32fk
Installing collected packages: hello
  Running setup.py install for hello: started
    Running setup.py install for hello: finished with status 'done'
Successfully installed hello-0.0.0
darwin /var/folders/4y/x7m68gms1cjcc8tpjlxcwz5h0005tq/T/tmp.ijKV32fk $ ./test
1
2
3
4
one
two
three
four
```

I see you are using `freeze_support`, are you running this on a windows machine? Fwiw, you should not need to run freeze_support within a shiv pyz.

**Comment by samclark2015** [comment]
Has there been any improvement on this? Our development group has pretty much cemented into using Shiv for application distribution and we encountered this same issue recently. 

Our systems are running RedHat 7.6, Python 3.7.5, Anaconda 4.8.2, and Shiv 0.4.0.

**Comment by lorencarvalho** [comment]
Hi @samclark2015, sorry to hear that, shiv's runtime is small and unobtrusive, so this behavior is very surprising. We use shiv internally at LinkedIn with many apps that use multiprocessing and multithreading with success. Do you have a recipe I can use to reproduce the issue you are facing?

**Comment by samclark2015** [comment]
Thanks for the response. Upon further investigation, the issue turns out to be unrelated to Shiv. Thank you for the great tool!

**Comment by lorencarvalho** [comment]
<3
