### ISSUE TITLE
Update click dependency

### ISSUE THREAD

**Issue by kontur** [linkedin/shiv#122]
Is there a pressing reason not to use click 7.0 as indicated by `click>=6.7,!=7.0` in the install requirements?

**Comment by lorencarvalho** [comment]
@kontur click 7.0 was errantly uploaded to PyPI with a capital letter (`Click` and not `click`) which causes problems when installed into environments that declare a dependency on `click<7.0` (lowercase) as pip will treat them as _different packages_. (see: https://github.com/pallets/click/issues/1284 for context)

Once a newer version is released with the lowercase spelling, it should get picked up automatically. I'm not sure why there hasn't been a click release in so long.

**Comment by kontur** [comment]
Ah, nasty hickup. Thanks for the clarification.
