### ISSUE TITLE
Make generated zipapps run on 3.5

### ISSUE THREAD

**Issue by jhermann** [linkedin/shiv#124]
Referring to #21, support for 2.7 is by now more than futile, but 3.5 is still a valuable target (concrete use-case at hand is Debian Jessie). What prevents it from running are minor things like encoding declarations and f-strings.

Would you be willing to accept downgrading PRs *for the code embedded in zipapps*?

**Comment by lorencarvalho** [comment]
I think it's far easier to continue to support the stated version range (3.6+), I'd rather not get into the business of having the tool (shiv) only work on 3.6+, but be able to produce pyz files that work on 3.5+. I can imagine that being very confusing.
