### ISSUE TITLE
[FEATURE] Inject the Python interpreter string

### ISSUE THREAD

**Issue by jhermann** [linkedin/shiv#125]
Expanding on my idea from #86, the string passed via `-p` could be injected with Python version information.

Initially, this would suffice (i.e. it's a one-liner):

    >>> "/usr/bin/env python{py.major}".format(py=sys.version_info)
    '/usr/bin/env python3'

And while this would be a potentially breaking change, the odds that someone has `{` in their bang path are quite low.

**Comment by jhermann** [comment]
```console
$ shiv -p '/usr/bin/env python{py.major}.{py.minor}' -o shiv .
…
$ head -n1 shiv
#!/usr/bin/env python3.6
```

**Comment by lorencarvalho** [comment]
Hi @jhermann,

I'm not sure I understand the intent here - when would a user want to leverage this feature as opposed to just giving the exact string?

**Comment by jhermann** [comment]
For example build scripts that handle different python versions of a project over time (as it progresses) or by configuration (in CI) get easier to handle. Just one less thing that can break,

**Comment by lorencarvalho** [comment]
I would prefer to leave that functionality up to the build script / build script author (seems like something that would be well served by Jinja or some other templated build script) and have shiv remain un-opinionated.
