### ISSUE TITLE
Issue executing bundle in the same manner as python -m <MODULE_NAME>

### ISSUE THREAD

**Issue by Alex-Mann** [linkedin/shiv#136]
I could be missing something here, but when trying to bundle up my python cli module in the typical setuptools form, it is not able to find any of my subpackages due to absolute path imports. Any ideas here?

Essentially I am getting the error message where:
```
  File "programmer/__main__.py", line 11, in <module>
    from programmer.configurator import configurator
ModuleNotFoundError: No module named 'programmer'
```

My project structure is like so:
```
top_folder_programmer/
  setup.py
  requirements.txt
  programmer/
    __init__.py
    __main__.py // contains the main function to execute cli()
    configurator/
      __init__.py
```

I'm calling shiv like so:
```
shiv -e programmer.__main__:cli -o programmer.pyz pyyaml xmltodict numpy --compressed
```

I'm able to reproduce the exact same error without bundling by calling the module like `python programmer`, when to really invoke it from the command line I need to call it like: `python -m programmer`.

Any help would be great.

**Comment by Alex-Mann** [comment]
Ok, I've found the PR shim and was able to replicate an environment similar to that which worked.. but now I have a resource file (a `csv` file) in a subfolder that is not getting picked up. How do you include additional files or even whole subdirectories with containing resources?

**Comment by lorencarvalho** [comment]
Hi @Alex-Mann,

When you say
> I've found the PR shim
What are you referring to? The error you are describing looks like `programmer` is not seen as a valid (importable) package. However, your project structure seems fine. I'd be curious to see the contents of your `setup.py` to see how you are discovering the package.

If you have a resource file, I recommend using the `importlib.resources` api in the stdlib (https://docs.python.org/3/library/importlib.html#module-importlib.resources). As long as the non-python files are inside of a package or subpackage, you should be able to load them using `importlib.resources`.

**Comment by Alex-Mann** [comment]
Hey,

Sorry I was referring to this [PR](https://github.com/linkedin/shiv/pull/127). I rearranged my source code and then shiv started picking it up correctly, but unfortunately, I couldn't get it to work so I abandoned it until I heard back here... I'll try to give some more details on the setup.

So the package structure is the same, except now I have:
```
top_folder_programmer/
  setup.py
  requirements.txt
  programmer/
    cli.py // cli code is in here
    __init__.py
    __main__.py // contains the main function to execute the imported main() func from cli.py
    configurator/
      __init__.py
```

The code for programmer/\__main\__.py looks like this:
```
from .cli import main

if __name__ == "__main__":  # pragma: no cover
    main()
```

The setup.py function looks like so:
```
import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="mss-programmer", # Replace with your own username
    version="0.5.0",
    author="Alexander Mann",
    author_email="EMAIL",
    description="A tool to help program X",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(),
    entry_points={
      'console_scripts': [
        'programmer = programmer.__main__:cli'
      ]
    },
    python_requires='>=3.7',
)
```

I actually am using the importlib library to import the csv. But I've abstracted it to a helper function that looks like:
```
// in folder /programmer/utils/path_helper.py
import inspect
import os.path
import importlib.resources

def get_file_path(package, filename):
    with importlib.resources.path(package, filename) as r: # context manager obj
        return os.path.abspath(r)
```
I then use this function inside of /programmer/configurator/configurator.py at the top like so:
```
import os
import sys
import math
import csv
import numpy
import os

import programmer.configurator

from programmer.utils.path_helper import get_file_path

ratecsv_filename = get_file_path(programmer.configurator, 'rate.csv')
```

Is using absolute paths for import OK for shiv? I am importing all subpackages everywhere by doing `import programmer.<SUB_PACKAGE>.<ETC>`

Also the command that I am using to compile with shiv is:
```
shiv -e programmer.__main__:cli -o programmer.pyz pyyaml xmltodict numpy --compressed
```
And then I run the result with: 
```
./programmer.pyz
```

I figured this out before, but right now I am getting the error:
```
Traceback (most recent call last):
  File "./programmer.pyz/_bootstrap/__init__.py", line 65, in import_string
ModuleNotFoundError: No module named 'programmer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amann/.pyenv/versions/3.7.5/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/amann/.pyenv/versions/3.7.5/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./programmer.pyz/__main__.py", line 3, in <module>
  File "./programmer.pyz/_bootstrap/__init__.py", line 179, in bootstrap
  File "./programmer.pyz/_bootstrap/__init__.py", line 69, in import_string
  File "./programmer.pyz/_bootstrap/__init__.py", line 50, in import_string
  File "/Users/amann/.pyenv/versions/3.7.5/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'programmer'
```
Assuming I fix this again, I am not sure why the resulting resources below programmer/programmer don't get bundled in.

Thanks again for the help.

**Comment by lorencarvalho** [comment]
Hi @Alex-Mann,

Are you including the package itself when creating the `pyz`? In the example you cite:

`shiv -e programmer.__main__:cli -o programmer.pyz pyyaml xmltodict numpy --compressed`

I don't see the `programmer` package itself being included, if you are in the root of the package (same $cwd as `setup.py`) you can just append a `.` to your command, otherwise the path to the package should suffice, or if you've published to PyPI you can specify it by name (like you've done for pyyaml xmltodict & numpy).

Hope that helps!

**Comment by Alex-Mann** [comment]
So what I ended up doing (which worked) was creating the following script. Maybe you have a better approach (ie. adding the `.` is a better solution).
```
#!/usr/bin/env bash

# clean old build
rm -rf dist programmer.pyz

pip install -r requirements.txt --target dist/
pip install . --target dist/

shiv --site-packages dist --compressed -p '/usr/bin/env python3' -o programmer.pyz -e programmer.cli:main
```

Another question... is there a way compress the package such that it cannot be unzipped/or that it obfuscates the python code? In a similar way that PyArmor does? PyArmor is a paid package which is a shame. Essentially I want to hand it off as a ~binary where the user cannot really see the source code.

**Comment by lorencarvalho** [comment]
Hi again @Alex-Mann,

So, what your script is doing is creating a site-packages (dist) and installing your package into it and then passing that prepared directory to `shiv` to pack into the `pyz`... You've implemented some of what `shiv` does under the covers for you! Adding `.` to your original command effectively does the same thing as your script. 

When shiv processes it's command line arguments, anything that isn't a shiv argument gets delegated to `pip`:
```
shiv -e programmer.__main__:cli -o programmer.pyz pyyaml xmltodict numpy --compressed .
      ^                          ^                    ^      ^     ^       ^          ^
      |                          |                     \     |    /        |          |
      |                          |                      \    |   /         |          |
      |                          |                       \   |  /          |          |
      | "entry point", shiv      | "outfile", shiv       these are         |         pip!
                                                         pip args!        shiv
```
The underlying pip command that is constructed and executed (via subprocess) looks like:
```
pip install pyyaml xmltodict numpy . --target /some/tmpdir
```
And then we pack that tmpdir into the `pyz`. :) 

---

As for your second question, regarding obfuscating the code, unfortunately this is outside the scope of what `shiv` was built to do. The resulting `pyz` files that it creates are not impermeable, and in fact whenever you execute a `pyz` it unzips the packed dependencies to a directory in `~/.shiv`, fully readable.

**Comment by Alex-Mann** [comment]
This is what I needed! Thanks for your help.

I know there are likely no future plans for this, but IMO, code obfuscation would be a very slick addition to this package.
