### ISSUE TITLE
How to include a local module in a shiv pyz ?

### ISSUE THREAD

**Issue by TTimo** [linkedin/shiv#139]
I ran into several problems building a simple example using shiv that packages a simple script and some dependencies. After a lot of iteration, here's what I've come up with: https://github.com/TTimo/shiv-example

This assumes you have `pipenv` and a few other things. I'm testing on an Arch system with Python 3.8

- As per https://github.com/TTimo/shiv-example/blob/f0d5b72eacd7b834e9cbd8ccdce317d77352f099/build_in_env.sh#L14 - I am not able to tell `shiv` to package my `demo` module directly, I am getting a "No matching distribution found for demo" error?

- Could `shiv` support "no dependencies", rather than passing some dummy module like in https://github.com/TTimo/shiv-example/blob/f0d5b72eacd7b834e9cbd8ccdce317d77352f099/build_in_env.sh#L17

- Finally, stuffing my module manually worked, but I may have run into a Python PYZ support bug: https://github.com/TTimo/shiv-example/blob/f0d5b72eacd7b834e9cbd8ccdce317d77352f099/build_in_env.sh#L20

**Comment by lorencarvalho** [comment]
Hi @TTimo,

`shiv` does not make any assumptions about what you are trying to package, so if you omit the path to the Python package, it won't be included.

In fact, the way that packages are installed is by delegating any non-shiv command arguments to `pip` (under the covers), so, if you were installing your "demo" package via pip, you would do so like `pip install .`, the same is true for `shiv`: `shiv -e demo.main -o demo.pyz .`

Hope that helps!

**Comment by TTimo** [comment]
Thanks! I was able to fix my example based on your suggestions. It didn't occur to me to try something like `shiv -e demo.main -o demo.pyz .`.
