### ISSUE TITLE
$SHIV_ROOT should default to $XDG_CACHE_HOME

### ISSUE THREAD

**Issue by rsyring** [linkedin/shiv#141]
Instead of having shiv's cache files go in `~/.shiv` by default, they should probably go in `$XDG_CACHE_HOME/.shiv` which defaults to `~/.cache/shiv`.

For reference: [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by lorencarvalho** [comment]
hi @rsyring,

I prefer the simplicity of `~/.shiv` over XDG_CACHE_HOME, specifically because if we were to adopt XDG I would want to use the venerable `appdirs`, but this logic would need to be used in the runtime (bootstrap) where I want to avoid _any_ third party library usage to keep the runtime small and bootstrapping it as simple as possible. I also am just personally unsure of the ubiquitousness of the XDG* variables, do they work on windows? I am certain that `~` will work cross platform.

Currently we respect a `SHIV_ROOT` environment variable to influence where the cache dir is unpacked at runtime, additionally I would not be opposed to an argument like `--xdg` to circumvent the default behavior, but I hesitate a little because I imagine that there'd need to be some additional checking in `shiv.bootstrap:cache_path` for the existence of the variable, etc.

**Comment by rsyring** [comment]
`appdirs` works on Windows. [It's a single file](https://github.com/ActiveState/appdirs/blob/master/appdirs.py), you could easily vendor it.  That's probably the better option, since it will use the XDG specification on Linux and OS standards on other platforms.

> Currently we respect a SHIV_ROOT environment variable to influence where the cache dir is unpacked at runtime,

I mentioned this in #88, but I'm going to do it again here b/c I think it's a really important point: I don't control the operating environments of the places I ship my application binaries to.  I can't set environment variables for them.  All I can do is give them a binary and tell them to use it.  They aren't the type of users who are going to care about or even really understand what cache files are and why they are accumulating on their system.  I, as the application developer and packager, need to care about those things for them.  I can't rely on any run-time mechanism to handle cache files.  I need to be able to have all the configuration setup at build time, which is the last step that I have control of in my usage workflow.

I realize if you run your binaries primarily as a way to ship applications at LinkedIn, you likely have full control of the servers and can set those environment variables at the OS or app level as part of your provisioning or deploy process.  But I'm primarily using shiv to package CLI commands for other users.

> I would not be opposed to an argument like --xdg to circumvent the default behavior

A build time argument?  If so, that's better than nothing.  But even then, why have two different code paths.  IMO, using the system "blessed" paths for cache directories should always be preferred.  Why have the default option be different from that if you are already going through the work in the code to support `appirs`?

Currently shiv drops a bunch of cache files in the home directory with no mechanism for cleanup and no indication to the system whatsoever that those files are cache files.  You indicate concern about this situation in #88, but that issue doesn't seem like it's going to get attention.  You have closed #142 and you seem hesitant about this, even though it reflects OS standards.

Just to be clear, if you don't really care about this, if the status quo works for you and LinkedIn's needs, and you don't want to take the chance of breaking things by changing shiv, just say so and I'll move on to a different tool or create my own personal fork with a few improvements.  I'm happy to contribute here and make some improvements if we can get on the same page.  But I don't want to be annoying or distracting you with my concerns about the cache files.

Please don't read anything negative into the above paragraph, I'm not upset or offended by this.  It's your project, it works for you as-is, that's great.  I just don't want to waste our collective time advocating for change here if our use cases and needs are just fundamentally different.

Thanks.  :)

**Comment by ClericPy** [comment]
These days I run .pyz file on Map/Reduce environment with `-file` arg of hadoop streaming, but I don't want to make too many cache files in default `~/.shiv` path (for there is no build_id to force generating the cache files in a same folder). So I have to set the SHIV_ROOT environment variable as cwd `./.cache`, is there a way to set a default cache path while building pyz file, or support the build_id to distinguish an app from others?
