### ISSUE TITLE
Tag shiv's cache directory so it can be ignored by backup software

### ISSUE THREAD

**Issue by rsyring** [linkedin/shiv#142]
For reference: https://bford.info/cachedir/

In short, drop a file in $SHIV_ROOT like:

```
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by (application name).
# For information about cache directory tags, see:
#	http://www.brynosaurus.com/cachedir/
```
Borg backup software, for instance, can ignore files based on this.  See [--exclude-caches](https://borgbackup.readthedocs.io/en/stable/usage/create.html)

**Comment by lorencarvalho** [comment]
hi @rsyring,

I can't be certain that every user/system administrator who uses `shiv` would want to exclude the cache dir from their backup software, so I do not want to make that assumption. Also, it seems to me that anyone administering backup software (borg included) could configure it to ignore `$HOME/.shiv` easily enough that this would not be required.

**Comment by rsyring** [comment]
To be clear, the presence of this tag file doesn't mean backup software will automatically exclude it.  As I noted above with Borg, `--exclude-caches` has to be passed to ignore cache directories.  While you could ignore `~/.shiv`, it requires manual configuration.  If you have 25 programs with cache directories, then 25 different settings in the ignore file.  

The presence of the cache tag file doesn't mean "ignore this directory in backups" it just means, "this is a cache directory".  What a program would choose to do with that piece of meta information, is up to the program.
