### ISSUE TITLE
Build with entry point having arguments

### ISSUE THREAD

**Issue by stevenluda** [linkedin/shiv#145]
Does anyone know how? It seems the resulting .pyz ignores any argument given to it when executing.

**Comment by lorencarvalho** [comment]
@stevenluda, can you clarify what you mean? Are you referring to trying to use an entry point that expects positional arguments? `shiv` follows the entry point specification as described here https://packaging.python.org/specifications/entry-points/

**Comment by stevenluda** [comment]
@lorencarvalho , yes, like def main(arg1:str) is my entry point.

**Comment by lorencarvalho** [comment]
@stevenluda gotcha, yeah that is not compliant with the specification for entry points (for example, you couldn't have an entry like that in setup.py's entry_points kwarg). So it's not something we support either, sorry!

If you want your application to be able to parse arguments, I recommend looking at `click`, `argparse` or `optparse`.
