### ISSUE TITLE
ModuleNotFoundError: No module named '_ldap' with shiv on remote machine

### ISSUE THREAD

**Issue by kush99993s** [linkedin/shiv#146]
Hello Team,

I loved shiv , it is great package. Currently I am facing following issue

I am using shiv to create python executable file as follows:

  ```
  shiv --site-packages dist \
        --compressed \
        -p '/usr/bin/env python3' \
        -o demo \
        -e demo.main:main \
        . -r requirement.txt
```

this demo zipapps works just fine in my machine. however, when I demo zipapps in remote machine, I am getting following error

`    ModuleNotFoundError: No module named '_ldap' with shiv on remote machine
`
If I run above code in remote machine to build demo zipapps, then run it works just fine. Do you know how to fix this. issue is coming from python-ldap library. But I am not sure how to fix it.

**Comment by lorencarvalho** [comment]
Hi @kush99993s,

Is the python-ldap package installed into "dist" or listed in `requirements.txt`?

**Comment by kush99993s** [comment]
sorry, I first used requirement now. I am trying to use dist

shell script for this is as follows
```

#!/usr/bin/env bash

# clean old build
rm -r dist demo

# include the dependencies from `pip freeze`
pip install -r requirement.txt --target dist/

# or, if you're using pipenv
# pip install -r  <(pipenv lock -r) --target dist/

# specify which files to be included in the build
# You probably want to specify what goes here
cp -r  -t dist project manage.py

# finally, build!
shiv --site-packages dist --compressed -p '/usr/bin/env python3' -o demo -e demo.main:main

```

However, still not working

**Comment by lorencarvalho** [comment]
The question still stands, though, is python-ldap included in `requirements.txt` and/or the `dist/` directory? It's also possible that the python-ldap library has system requirements, like a shared library that needs to be installed on whatever system it's being used on.

**Comment by kush99993s** [comment]
i have put requirements.txt there fore it is present in dist. python-ldap do have system requirement. I have install those requirements in remote machine as well. My and remote machine both are Ubuntu 18.  Python-ldap don't have wheel like psycopg2-binary.

**Comment by kush99993s** [comment]
I found solution in using -sE in python
