### ISSUE TITLE
Set default $SHIV_HOME as CWD while packaging?

### ISSUE THREAD

**Issue by ClericPy** [linkedin/shiv#155]
Is there a way to set the default SHIV_HOME path with current work dir?

These days I used app.pyz which packaged with shiv and raised an error for missing the HOME path on hadoop data nodes.

So could I set the default shiv cache folder path as ./_shiv_cache instead of ~/.shiv, without any environment variable?

**Comment by lorencarvalho** [comment]
Hi @ClericPy,

> raised an error for missing the HOME path
Can you paste the exact error (and stack trace, I presume) that you get? 
I'm curious about how `Path("~/.shiv").expanduser()` handles a missing `HOME` variable in your environment. On my machine (a macbook):

```
darwin ~ $ HOME="" python3
Python 3.8.2 (default, Aug 10 2020, 05:49:21)
[Clang 12.0.0 (clang-1200.0.31.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> pathlib.Path("~/.shiv").expanduser()
PosixPath('.shiv')
```

So, if `HOME` is missing, shiv's bootstrap runtime _ought_ to default to `.shiv` in the $PWD.

**Comment by ClericPy** [comment]
> hadoop-streaming -files "a.pyz" -input "/xxx/*" -output "/tmp/test" -mapper "python3 a.pyz"

I run the cmd again, and got the permission errors like below

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "a.pyz/__main__.py", line 3, in <module>
  File "a.pyz/_bootstrap/__init__.py", line 187, in bootstrap
  File "a.pyz/_bootstrap/__init__.py", line 114, in extract_site_packages
  File "/usr/lib64/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/.shiv'
```

So, could I set `.shiv` path in a given path instead of reading the environment variable SHIV_HOME while I was dumping the pyz file, not while it is running? Such as `python3 -m shiv -o test.pyz --cache-path="./shiv_cache bottle"`

**Comment by lorencarvalho** [comment]
hi @ClericPy, I went ahead and created a PR with this feature, it works with relative paths so it should solve your issue :)

Thanks for the report!

**Comment by ClericPy** [comment]
@lorencarvalho 
Thanks a lot! These really do me a favor, when is its released time?

For some app.pyz with a very frequent changing, run app.pyz will alway create a new build-cache folder in the SHIV_HOME path, which makes me use shiv only as the alternative of venv. Is there a way to overwrite the special cache folder in SHIV_HOME path to reuse same pyz cache files for same file_name / build_id shiv package?
