### ISSUE TITLE
How to use multiple shiv pyz files in one calling?

### ISSUE THREAD

**Issue by ClericPy** [linkedin/shiv#157]
Just like:

> python3 bottle.pyz loguru.pyz script_using_bottle_and_loguru.py

For now, I use shiv as venv zip files to distribute python code and env, so that pyz only need to be dumped once for different products.

**Comment by lorencarvalho** [comment]
Hi @ClericPy,

Just to make sure I understand, are you asking how to use multiple discrete `pyz`s made with shiv to invoke a single script?
Is your idea to basically layer two virtualenvironments on top of each other?

I think there may be dragons here, layering virtual environments is theoretically possible but there could be issues with precedence or transitive dependencies. That said, it's not entirely unorthodox to use `site.addsitedir` to pick up additional site-packages directories. A small script like the following might work:

```
#!/usr/bin/env python3

import json
import site

from pathlib import Path

pyz_1 = Path("/path/to/bottle.pyz")
pyz_2 = Path("/path/to/loguru.pyz")

for pyz in (pyz_1, pyz_2):
    zip_file = zipfile.ZipFile(pyz)
    data = json.loads(zip_file.read("environment.json"))
    site.addsitedir(f"~/.shiv/{pyz.name}_{data['build_id']}/site-packages")
```

**Comment by ClericPy** [comment]
Thanks a lot for your reply, @lorencarvalho 
This is quite a magic choice, I have never thought that way to resolve it. And is that a good choice for using pyz as a or many virtual environments? These two months I have used `shiv` in lots of hadoop streaming projects, and recommend it to colleagues. If it's a bad usage (as the venv zip file), I will get rid of this habit.

**Comment by lorencarvalho** [comment]
@ClericPy I don't know if I'd call it a "good" choice, it's just something I've used in the past to cobble together an environment from multiple PYZs. Using a single pyz as a venv zip file is definitely not bad usage of shiv, that's one of it's intended usages. The only issues that could arise are if you are wanting to use N+1 pyzs together. It's better to create a single PYZ with all the deps you want, rather than trying to stitch a few together, if that makes sense.

thanks

**Comment by ClericPy** [comment]
@lorencarvalho `shiv` has given me a big hand while running `hadoop streaming` jobs, thank you for this amazing lib (even much better than alternatives). For the venv usage, you are right, I would better shiv all the requirements in one pyz.

For now what confused me is to make the cache folder unique (like the build_id), or set cache folder path while dumping (not running with env variable SHIV_HOME), but these things is not very important.

I love this lib, it makes python could run as a standalone tool in its own way.

Best wishes, and thank you for your reply. ^-^
