### ISSUE TITLE
shiv pre-commit: not working together

### ISSUE THREAD

**Issue by diefans** [linkedin/shiv#160]
Just want to have your opinion on this comment: https://github.com/pre-commit/pre-commit/issues/1602#issuecomment-694947834

In fact I believe, the issue is on pre-commit's side...

**Comment by lorencarvalho** [comment]
Hi @diefans,

This isn't so much a bug with either program, just an incompatibility with their respective designs.

The `pre-commit` tool has an "install" command that creates scripts in `.git/hooks` to invoke the `pre-commit` executable. The way this hook is installed can be found in `pre_commit/commands/install_uninstall.py` but suffice to say it drops a templated executable script into `.git/hooks/pre-commit` that contains the following logic:

    if os.access(INSTALL_PYTHON, os.X_OK):
        CMD = [INSTALL_PYTHON, '-mpre_commit']

So this invokes the interpreter (`INSTALL_PYTHON`, which looks to be populated with my computer's Python 3 path) with `-mpre_commit`. The `pre-commit` executable made with shiv is not invoked at all, so you get the following error:

    darwin ~/tmp git:master ✓ $ git commit --allow-empty -m 'test'
    /export/apps/python/3.8/bin/python3: No module named pre_commit

If I modify the installed hook to use the pyz I created for `pre-commit`, then it works as expected:

    
    darwin ~/tmp git:master ✓ $ head -n 1 .git/hooks/pre-commit
    #!/usr/bin/env python3
    ...
    darwin ~/tmp git:master ✓ $ head -n 1 .git/hooks/pre-commit
    #!/usr/bin/env SHIV_INTERPRETER=1 pre-commit

    darwin ~/tmp git:master ✓ $ git commit --allow-empty -m 'test'
    No .pre-commit-config.yaml file was found
    - To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
    - To permanently silence this, install pre-commit with the --allow-missing-config option
    - To uninstall pre-commit run `pre-commit uninstall`

I don't think there is any way to influence the INSTALL_PYTHON variable that these scripts are created with, https://github.com/pre-commit/pre-commit/blob/8f32c5b929ca99e4d396d27b993017f821f6670a/pre_commit/commands/install_uninstall.py#L103

So yeah, it's more of a compatibility issue, not really a bug on either side.

**Comment by diefans** [comment]
hmmmm .... I don't want to point fingers, but to sum up your comment (and also my opinion) shiv can do nothing to fix this but the way the hook in pre-commit is created, could be changed to overcome this issue (sadly pre-commit devs don't feel responsible).

At least for me and for the zipapp concept at all, it feels wrong to assume that the actual python interpreter has a certain module installed.
