### ISSUE TITLE
allow use generic "/usr/bin/env python3.6" shebang?

### ISSUE THREAD

**Issue by anthrotype** [linkedin/shiv#17]
Hello,

I played a bit with shiv and noticed that it always writes the full path to a python interpreter (sys.executable or user provided one) in the zipapp's shebang. Which means, if I try to run the same pyz on a different machine where python3.6 is installed in a different location, it won't run.

https://github.com/linkedin/shiv/blob/29fb7c316fa7b1f9111cade730b2168a2c4f4a6e/src/shiv/cli.py#L56

https://github.com/linkedin/shiv/blob/29fb7c316fa7b1f9111cade730b2168a2c4f4a6e/src/shiv/builder.py#L39-L43

https://github.com/linkedin/shiv/blob/29fb7c316fa7b1f9111cade730b2168a2c4f4a6e/src/shiv/pip.py#L46

With [pex](https://pex.readthedocs.io/en/stable/buildingpex.html#invoking-the-pex-utility), one can specify the interpreter to use either as absolute path or just the name of a Python interpreter within the environment.

It would be nice if shiv also allowed to do that.

Thank you

**Comment by anthrotype** [comment]
oh I see you're already addressing this issue in https://github.com/linkedin/shiv/pull/7 :+1: 

> Stop enforcing that --python exists, since you might be creating a .pyz file for a different machine.

**Comment by sixninetynine** [comment]
hey @anthrotype 

I've never been a big fan of how I implemented this (the shebang/interpreter handling stuff) and as you rightly point out it comes up in #7 as well.

What do you think would be the best path moving forward? There's a few options:

1.) always use `/usr/bin/env` and hope that users have <=3.6 in their path
2.) inspect the argument to `-p` and if it is determined to be a path use it as shebang, if not a path assume it's a path element to be used with `/usr/bin/env`
3.) have multiple options specifying if you want a full interpreter path or a `/usr/bin/env` path... say mutually exclusive `--env python3` and `--shebang /path/to/python3` or something like that?

**Comment by anthrotype** [comment]
I think option (2) would be the simplest one. If it is a real path (maybe check if it's absolute as well?) then use it as is, if not maybe check that `shutil.which` returns something (so that the later pip subprocess won't fail) and store the shebang with /usr/bin/env. Something like that.

**Comment by sixninetynine** [comment]
Something like this perhaps? 

```
>>> def real_path_or_env(path: Path):
...     if path.is_file() and path.is_absolute():
...         return path.as_posix()
...     else:
...         return f"/usr/bin/env {path.stem}"
...
>>> possibilities = [Path('python3'), Path('/export/apps/python/3.6/bin/python3'), Path('bin/python')]
>>> for poss in possibilities:
...     print(real_path_or_env(poss))
...
/usr/bin/env python3
/export/apps/python/3.6/bin/python3
/usr/bin/env python
```

I'm a little worried about the 3rd case here, where `/usr/bin/env python` will only be a python3 interp if the machine running the pyz has python3 first in their $PATH. I'm not sure what to do about that (if anything?)

**Comment by warsaw** [comment]
Maybe a single option which explicitly names the shebang line?  E.g. `--shebang "/usr/bin/env python3"`.  EIBTI

**Comment by anthrotype** [comment]
pex is fine with a single --python option. But i'm ok if you prefer to go for an explicit --shebang option

**Comment by sixninetynine** [comment]
@warsaw @anthrotype 

I was thinking a good middle ground here would be to take whatever value is given to `--python` and plop it behind `#!/usr/bin/env`, this would work for full paths as well as path elements, however in testing that turned out to not be the case:

```
❱❱❱ ./t.py
/usr/bin/env: /export/apps/python/3.6/bin/python -sE: No such file or directory
```
Though that _does_ work on OSX :/

That said, I think we can be  little less particular about what gets passed in to be the shebang and not so picky about full paths that exist on the build machine.

**Comment by hawkeyej** [comment]
@warsaw I like the explicit approach and it's Zen of Python compatible....
> Explicit is better than implicit.

**Comment by borgstrom** [comment]
I think the test should be if `os.path.sep` is in what's passed to `--python` then it is resolved to an absolute path and the shebang line uses that, otherwise env is used with whatever value is provided.

Whatever the solution, I'd like to see the shiv builder output the value of the shebang line while running.

**Comment by warsaw** [comment]
@borgstrom That seems like a good heuristic/compromise, and I agree that the output should display what is *actually* used in the shebang.

**Comment by sixninetynine** [comment]
I agree as well! I went through this a bit over the weekend and I should have something shortly. The only snag is handling how we invoke `pip`... I'm thinking that as long as we are loud about 3.6 being a requirement we can just use `sys.executable`'s pip (since shiv declares it as a dep, so we can be confident it's there)

**Comment by sixninetynine** [comment]
another snag is the fact that we add `-s` and `-E` to our invocation of the python interpreter. Using `env` doesn't allow us to supply arguments to the interpreter on linux 😞

**Comment by anthrotype** [comment]
Thank you 😊

**Comment by sixninetynine** [comment]
So just to fully close the loop here, you can now specify anything you like to `--python` and it will be prepended to the resulting `pyz` as your shebang. 

The value provided to `--python` should be anything _after_ `#!`, so for example:

    shiv -c pipenv -o ~/bin/pipenv --python "/usr/bin/env python3.6" pipenv pew

or
    shiv -c pipenv -o ~/bin/pipenv --python "/opt/alternate/python3 -sE" pipenv pew

Both will work and do not require the targeted shebang to exist on the local filesystem.
