### ISSUE TITLE
Automatically look up entry point corresponding to a console script?

### ISSUE THREAD

**Issue by inklesspen** [linkedin/shiv#175]
I'm using shiv to deploy a web application. I've set my shiv entry point to the most commonly used entry point (starting the web server), but I will use others from time to time; both provided by libraries I'm using (Pyramid's `pshell` and Alembic's `alembic`, as well as console scripts I've written myself. All of these scripts are listed in the `console_scripts` sections of their dist info.

However, when I use `SHIV_ENTRY_POINT`, I have to look up (or remember) that the `alembic` console script corresponds to the entry point `alembic.config:main`. It would be nice if there were a `SHIV_CONSOLE_SCRIPT` configuration option to automatically look that up for me. Is this doable without too much difficulty?

**Comment by inklesspen** [comment]
If looking up the entry points from the dist info is annoying, a good alternative would be if I could list several entry points when creating the shiv, and then pick between them when running it.

Something like `shiv -o myapp.pyz --alternate_script alembic=alembic.config:main` and then `SHIV_SCRIPT=alembic ./myapp.pyz`.

**Comment by lorencarvalho** [comment]
Hi @inklesspen - just released this feature with `0.5.0` https://github.com/linkedin/shiv/releases/tag/0.5.0
Thanks for raising the issue!
