### ISSUE TITLE
how to package hello world

### ISSUE THREAD

**Issue by qbit-git** [linkedin/shiv#182]
test.py
```
print('hello world')
```
how to use shiv package test.py ?

**Comment by lorencarvalho** [comment]
Hi @qbit-git,

shiv expects to work with Python _packages_ (i.e. something that is pip installable), if you were to take `test.py` and package it (via setuptools or pyproject.toml, etc) you could create an executable for it using shiv.

**Comment by qbit-git** [comment]
> Hi @qbit-git,
> 
> shiv expects to work with Python _packages_ (i.e. something that is pip installable), if you were to take `test.py` and package it (via setuptools or pyproject.toml, etc) you could create an executable for it using shiv.

It explains why shiv not enough popular: no hello world 😂

**Comment by lorencarvalho** [comment]
I updated the documentation and added a Hello World example, hope that helps 

thanks

**Comment by qbit-git** [comment]
> I updated the documentation and added a Hello World example, hope that helps
> 
> thanks

Thanks for your update.
But I still don't know how to package local py file to pyz with shiv. For example:
`pyproject.toml`
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["qbit"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "~2.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
`test.py`
```
import requests

def test():
    r = requests.get(r'http://www.httpbin.org/get')
    print(r)

if __name__ == '__main__':
    test()
```

**Comment by lorencarvalho** [comment]
Ah, you're right. I should use pyproject in the example code. It's more modern :)

You're super close! What you have there is actually a perfectly valid Python package, so it works with `shiv` just fine:

    git clone https://github.com/lorencarvalho/shiv-182.git
    cd shiv-182
    shiv -o test.pyz -p "/usr/bin/env python3" .
    ./test.pyz
    import test
    test.test()

The only missing piece is that you have no entry_point or console_script defined, you can manually provide the entry_point to `shiv` itself:

    shiv -o test.pyz -p "/usr/bin/env python3" -e "test:test" .
    ./test.pyz
    
Or you can bake it into your package metadata. I see that you are using Poetry, so that would be done by adding the following lines to the `pyproject.toml` file:

    [tool.poetry.scripts]
    test = "test:test"

And then specifying the console_script to `shiv`:

    shiv -o test.pyz -p "/usr/bin/env python3" -c test .
    ./test.pyz

Hope that helps!

**Comment by qbit-git** [comment]
I test your way. It can build, but it can not run. (Ubuntu 20.04/Python 3.8)
``` shell
~/shiv/shiv-182$ ll
total 20
drwxrwxr-x 3 qbit qbit 4096 Jul  5 17:19 ./
drwxrwxr-x 3 qbit qbit 4096 Jul  5 17:01 ../
drwxrwxr-x 8 qbit qbit 4096 Jul  5 17:01 .git/
-rw-rw-r-- 1 qbit qbit  313 Jul  5 17:10 pyproject.toml
-rw-rw-r-- 1 qbit qbit  134 Jul  5 17:01 test.py

~/shiv/shiv-182$ python3 test.py 
<Response [200]>

~/shiv/shiv-182$ shiv -o test.pyz -p "/usr/bin/env python3" -e "test:test" .
Processing /home/qbit/shiv/shiv-182
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting requests<2.26.0,>=2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Building wheels for collected packages: test
  Building wheel for test (PEP 517): started
  Building wheel for test (PEP 517): finished with status 'done'
  Created wheel for test: filename=test-0.1.0-py3-none-any.whl size=1276 sha256=73e91b076a913ffda5ba03d8f86c20fb458a506933c9bdb8420ec6c24bf1d41f
  Stored in directory: /home/qbit/.cache/pip/wheels/12/56/33/03eb391044d8d693df6785100872feab6b2f0a0d2ec208ca6d
Successfully built test
Installing collected packages: certifi, idna, urllib3, chardet, requests, test
Successfully installed certifi-2021.5.30 chardet-4.0.0 idna-2.10 requests-2.25.1 test-0.1.0 urllib3-1.26.6

~/shiv/shiv-182$ ./test.pyz 
Traceback (most recent call last):
  File "./test.pyz/_bootstrap/__init__.py", line 85, in import_string
AttributeError: module 'test' has no attribute 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./test.pyz/__main__.py", line 3, in <module>
  File "./test.pyz/_bootstrap/__init__.py", line 244, in bootstrap
  File "./test.pyz/_bootstrap/__init__.py", line 88, in import_string
ImportError: module 'test' has no attribute 'test'

```

**Comment by lorencarvalho** [comment]
@qbit-git can you confirm that your `test.py` file matches [what is in the shiv-182 repository](https://github.com/lorencarvalho/shiv-182/blob/9652c2e67818b4b06fa3b0dca19206a1e9339c39/test.py)? Python entry points format maps an import to a callable,

> The syntax for entry points is specified as follows:
> 
> `<name> = [<package>.[<subpackage>.]]<module>[:<object>.<object>]`
>
> where name is the name for the script you want to create, the left hand side of : is the module that contains your function and the right hand side is the object you want to invoke (e.g. a function).

 -- https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html 

So, in order for the entry point `test:test` to work, you need to be able to import & call it like `from test import test; test()`. A good way to diagnose errors like this is to try from an interpreter (so, `SHIV_INTERPRETER=1 ./test.pyz` and then attempt the import).

**Comment by qbit-git** [comment]
@lorencarvalho The code clone from  your repository.
``` python
~/shiv/shiv-182$ ll
total 24
drwxrwxr-x 4 qbit qbit 4096 Jul  8 08:42 ./
drwxrwxr-x 3 qbit qbit 4096 Jul  5 17:01 ../
drwxrwxr-x 8 qbit qbit 4096 Jul  5 17:01 .git/
drwxrwxr-x 2 qbit qbit 4096 Jul  8 08:41 __pycache__/
-rw-rw-r-- 1 qbit qbit  313 Jul  5 17:10 pyproject.toml
-rw-rw-r-- 1 qbit qbit  134 Jul  5 17:01 test.py

~/shiv/shiv-182$ cat test.py 
import requests

def test():
    r = requests.get(r'https://www.httpbin.org/get')
    print(r)

if __name__ == '__main__':
    test()
```
run py:
``` python3
~/shiv/shiv-182$ python3 test.py 
<Response [200]>

~/shiv/shiv-182$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir()
['__pycache__', 'test.pyz', '.git', 'test.py', 'pyproject.toml']
>>> import test
>>> dir(test)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'requests', 'test']
>>> test.test()
<Response [200]>
```
run pyz， dir(test) no test
``` python
~/shiv/shiv-182$ SHIV_INTERPRETER=1 ./test.pyz
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import test
>>> dir(test)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> test.test()
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
AttributeError: module 'test' has no attribute 'test'
```
