### ISSUE TITLE
Leverage pyz startup speed on small machines

### ISSUE THREAD

**Issue by g0di** [linkedin/shiv#201]
At my company we deploy shiv pyz files on some container orchestrator were we try as much as possible to limit the allocated resources per app.

It happens a lot that 0.1 cpu cores and 128mib of memory is enough to make the app run smoothly. 

However, doing so make the pyz startup time really slow because it needs to first unzip the archive into the shiv root folder. As soon as we increase the resources the startup time really decrease.

I was just wondering if there was some way to leverage this without having to increase allocated resources « just for » unzipping the pyz archive.

By the way, thanks for this great package.

**Comment by lorencarvalho** [comment]
Hi @g0di,

In your image configuration you could "run" the `pyz` in order to pre-extract it, which would theoretically preserve the cached dependencies in the image itself. Your image size would grow, but you wouldn't have to pay the extraction cost when you start it up. Here's a simple example:

```
$ shiv -c http httpie -o httpie.pyz
$ cat Dockerfile
FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3
COPY ./httpie.pyz /
# Run the pyz to trigger extraction
RUN /httpie.pyz --help
...
Calling the `pyz` will trigger extraction _at build time_, and then when you run the image on your infrastructure, the extracted dependencies will already be present in the image's volume, so no need to re-extract.

Hope that helps!

**Comment by g0di** [comment]
Thank you for you reply. Indeed this a good way of solving my issue. However I’m using shiv in particular to avoid to use Docker images. Basically I build the pyz file and let Marathon Mesos download then run it. I’m unsure there is any other way to handle my issue anyway… still, thanks a lot for your help and this wonderful library ;)

**Comment by lorencarvalho** [comment]
@g0di ah, I see. In that case, I think the only other way to reduce resource consumption during bootstrapping of the `pyz` would be to disable zip compression so that it's not as CPU intensive to extract. https://shiv.readthedocs.io/en/latest/cli-reference.html#cmdoption-shiv-compressed `--uncompressed`

The file will be larger, but should be quicker/less resource-heavy to unpack.

**Comment by g0di** [comment]
Indeed I think this is the only thing I can do. However, I can ask marathon to extract the pyz once downloaded (done outside of the container so with full CPUs available), may I use this to somehow « manually » extract the pyz before running it? The issue is that I’m not sure I can predict the name of the folder where I should extract it in order to make it use that folder instead of unzipping again at run
