### ISSUE TITLE
shiv can't create pyzs that run on Python 2

### ISSUE THREAD

**Issue by rouge8** [linkedin/shiv#21]
```
$ shiv -p $(which python2.7) vex -o vex.pyz && ./vex.pyz --version
 shiv! 🔪
Collecting vex
  Using cached https://files.pythonhosted.org/packages/71/78/c258893bbd82d09053397140e3aea86db0107f90434855e890c04a632e45/vex-0.0.18-py2.py3-none-any.whl
Collecting virtualenv (from vex)
  Using cached https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl
Installing collected packages: virtualenv, vex
Successfully installed vex-0.0.18 virtualenv-15.2.0
 done
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./vex.pyz/__main__.py", line 2, in <module>
  File "./vex.pyz/_bootstrap/__init__.py", line 57
    return root / f"{name}_{build_id}"
                                     ^
SyntaxError: invalid syntax
```

**Comment by rouge8** [comment]
Actually I can't get `shiv -p /usr/bin/python2.7 -e awscli.clidriver:main -o aws awscli && ./aws --version` to work on any commit in shiv's history...

**Comment by sixninetynine** [comment]
You are correct, `shiv` is an exclusively Python 3 cli and only creates `pyz` files that work on Python3.

I _believe_ you can create 3.5+ `pyz`s but it's only tested against 3.6

**Comment by rouge8** [comment]
Oh! For some reason I thought it was just that the CLI was Python 3.6 only, but that the `pyz` files could be created for either. Probably just an assumption coming from pex.

**Comment by rouge8** [comment]
If I came up with a PR making the bootstrap Python 2/3 compatible and covered it in the tests, would you be interested? I don’t want to spend time on it if you’d (understandably) rather stick with the simplicity of Python 3 only

**Comment by sixninetynine** [comment]
It's something we discussed internally (prior to open sourcing), and the conclusion we came to was that it would impose a support load we're not interested in (supporting py2). Definitely appreciate the offer though!
