### ISSUE TITLE
Error while finding module specification for '__main__' 

### ISSUE THREAD

**Issue by oussama-he** [linkedin/shiv#228]
I'm trying to create a zipapp for a simple Django project but I'm getting this error when trying to run it like this `./solution.pyz` or `python3 solution.pyz`:
```
Error while finding module specification for '__main__' (ValueError: __main__.__spec__ is None)
```
The project structure looks like this:
![image](https://user-images.githubusercontent.com/18425315/199477111-f03e163b-7c68-42b5-8e9f-465c8527b07d.png)

And this is the content of the main.py and build.sh files:
**main.py**
```py
import os
import sys

import django

# setup django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "solution.settings")
django.setup()

try:
    production = sys.argv[1] == "production"
except IndexError:
    production = False

if production:
    import gunicorn.app.wsgiapp as wsgi

    # This is just a simple way to supply args to gunicorn
    sys.argv = [".", "solution.wsgi", "--bind=0.0.0.0:80"]

    wsgi.run()
else:
    from django.core.management import call_command

    call_command("runserver")

```
**build.sh**
```
#!/usr/bin/env bash

# clean old build
rm -r dist solution.pyz

# include the dependencies from `pip freeze`
pip install -r <(pip freeze) --target dist/

# or, if you're using pipenv
# pip install -r  <(pipenv lock -r) --target dist/

# specify which files to be included in the build
# You probably want to specify what goes here
cp -r \
-t dist \
core manage.py db.sqlite3 solution

# finally, build!
shiv --site-packages dist --compressed -p '/usr/bin/env python3' -o solution.pyz -e solution.main
```

**Comment by lorencarvalho** [comment]
while I don't immediately recognize the error message you are getting, one thing you may be missing is including the local project in your `dist` directory before invoking `shiv`. In your build.sh script, it will only install the local package ("solution") if you've install it into the local virtual environment (via `pip install -e .` or a similar method).

**Comment by lorencarvalho** [comment]
feel free to re-open if needed
