### ISSUE TITLE
Should -c hello.py be expected to build ?

### ISSUE THREAD

**Issue by Imaclean74** [linkedin/shiv#41]
running : 

shiv  -c hello.py -o hello.pyz <somedep>

Fails with 

"No entry point 'hello.py' found in the console_scripts!"

whereas : 
shiv  -e hello:main -o hello.pyz <somedep>

succeeds.  I guess the console script needs to reside in some package ? either from a dependency or in the app source tree. But for a naive new user - you'd kind of expect it to work.

**Comment by sixninetynine** [comment]
Hi @Imaclean74 

The `-e` and `-c` arguments do presuppose some knowledge of how setuptools' entrypoints (and specifically the `console_scripts` entry point) work. Initially we only supported `-e` with the intent on being explicit about what python callable you want to "burn in" as the entry point to your pyz. I later added `-c` as a convenience for building third party tools (such as the example given in the docs for `pipenv`... I wouldn't know what pipenv's main entry point is without looking at the source code, but I know the `console_scripts` entry is `pipenv` just from having used it). 

So `-e` just presumes you know what you are providing (an importable callable). This can cause breakage at _run time_. Conversely, `-c` searches the `console_scripts` of all your dependencies and can cause breakage at _build time_. 

I'd love to improve the UX of these options! What do you think would help?

**Comment by devxpy** [comment]
@sixninetynine Thanks for this explanation. Please put this in the readme..

I was really confused by the difference between `-e` and `-c`

**Comment by devxpy** [comment]
Another query: 

Does passing `-e` also copy the source code for my app?

It looks like it doesn't, because the zipapp is affected by changes I do in my code, outside the zipapp.

Is there any way to bundle my app source code with the zipapp?
