### ISSUE TITLE
Writing ~/.pydistutils.cfg affects parallel builds.

### ISSUE THREAD

**Issue by zvezdan** [linkedin/shiv#49]
In build systems that allow products to build multiple Python packages (apps) together in parallel, such as PyGradle, the solution from #16 breaks the build of a package that does not use shiv. It was implemented in #27 but we did not notice until now the negative effect it has.

Since that solution is implemented only for homebrew Python, I believe it's unacceptable that it breaks standard Python builds and packages. We need to make this usage conditional, with some setting, so that users who need it can apply it, but the standard usage should not be doing this by default.

I'm inclined to just plain revert #27 to get the fix out ASAP.
Users who need this change can use the releases of shiv that have it, and later can use the future release of shiv that implements this conditionally.

Can we execute this plan promptly?
Thanks!

**Comment by sixninetynine** [comment]
cc @rouge8

**Comment by rouge8** [comment]
I would say go for whichever you think is the more important use case. I think https://github.com/pypa/pip/pull/4557 is the upstream pip issue which looks like it's back to life and will hopefully make it into the next pip release 🤞

**Comment by sixninetynine** [comment]
```

**Comment by warsaw** [comment]
Does `--no-user-cfg` work for this problem?

Relevant issues upstream:

* https://bugs.python.org/issue1180
* https://bugs.python.org/issue34389

**Comment by sixninetynine** [comment]
@warsaw only for source dists, not for wheels :(

**Comment by warsaw** [comment]
Well, that's unfortunate.  It won't help right away, but we should look into fixing this upstream.

**Comment by zvezdan** [comment]
It gets worse though, even without an enterprise build system.

Here's a simple experiment that proves how broken this is.
Build something with shiv (project A) in one terminal session and in another build another app that does **not** use shiv (project B) -- at the same time. For example start commands one after the other. The project B build will break because of the custom `~/.pydistutils.cfg` stored during its build from project A build.

This proves that changing *shared* _distutils_ settings in `~/pydistutils.cfg` is not an acceptable solution at all, under any circumstances. If the build is going to change _distutils_ settings at all, it must do that **local** to the project built by _shiv_ **only**.

Thus, as I suggested, let's revert this bug, to get a good release, and than carefully plan a workaround for _homebrew_ Python users that is localized to one project build.

**Comment by sixninetynine** [comment]
@zvezdan I agree, thanks for clarifying the scope

**Comment by sixninetynine** [comment]
reverted in #50
