### ISSUE TITLE
Pluggable setup process

### ISSUE THREAD

**Issue by ipmb** [linkedin/shiv#53]
Would you consider a PR which made the setup process (currently supporting `pip`/`setuptools`) pluggable so projects using alternate build systems could work with shiv? I'm interested in [poetry](https://poetry.eustace.io/), but others like [flit](https://flit.readthedocs.io/en/latest/) or [pipenv](https://docs.pipenv.org/) could be supported as well.

**Comment by ipmb** [comment]
On second thought, waiting for https://github.com/pypa/pip/issues/5407 is probably the way to go.

**Comment by sixninetynine** [comment]
@ipmb I'm also keeping a keen eye on the pep517 pip PR :)
